### ISSUE TITLE
Change React Hook names

### ISSUE THREAD

**Issue by baransu** [jeddeloh/rescript-apollo-client#39]
Right now for both queries and mutation, there is `use` function generated. I'm wondering if it would be possible to change it to `useQuery` for queries and `useMutation` for mutations. It would make it more readable if this module is a query or mutation.

**Comment by jfrolich** [comment]
I think it should be clear enough from the graphql definition. If that is not enough you can name the query module like `UserQuery.use`.

**Comment by baransu** [comment]
Probably right but `useQuery`/`useMutation` is more idiomatic in React/GraphQL world. And with autocompletion typing five more characters don't do the difference.

**Comment by jeddeloh** [comment]
Take the two situations:

**"I can't understand what `User.use` is, so it's better if it is `User.useQuery`."**

and

**"I can't understand what `User` is, so it's better if it's `UserQuery.use`."**

Only the latter is understandable both at the call site and as a module, and the generic `.use` hook (I think) helps push people in that direction. Personally, my projects always tend to end up with some sort of structure like `Queries.User.use` but I don't know about others.

When I initially went down this path, I also intentionally didn't want to call it `useQuery` because I wanted to hint this was a different pattern that was contextually tied to the module it resides in. I wanted you to think of the module as a first-class entity that could be passed around and name it as such.

Finally, the `.use` just brings me joy for some reason. I don't know why!

Anyway, this isn't a rejection of the issue, just presenting my viewpoint and would love to hear other thoughts.

**Comment by jeddeloh** [comment]
Closing this. Happy to revisit whenever, though.
